import { useRef, useState, type FormEvent } from 'react';
import type { ApiResult, RunMode, StartRunInput } from '../../shared/contracts';
import { startRunInputSchema } from '../../shared/schemas';
export function NewRunForm({ onStart, busy }: { onStart(input: StartRunInput): Promise<void>; busy: boolean }) {
  const [targetUrl, setUrl] = useState(''), [outputDirectory, setDirectory] = useState(''), [mode, setMode] = useState<RunMode>('standard'), [maxConcurrency, setConcurrency] = useState(4), [authorized, setAuthorized] = useState(false), [errors, setErrors] = useState<Record<string, string>>({}), [choosing, setChoosing] = useState(false), [showUrl, setShowUrl] = useState(false); const urlRef = useRef<HTMLInputElement>(null), directoryRef = useRef<HTMLButtonElement>(null), authRef = useRef<HTMLInputElement>(null);
  const submit = async (e: FormEvent) => { e.preventDefault(); if (busy || choosing) return; const input = { targetUrl, outputDirectory, mode, maxConcurrency, authorizationConfirmed: authorized }; const parsed = startRunInputSchema.safeParse(input); if (!parsed.success) { const next: Record<string, string> = {}; for (const issue of parsed.error.issues) next[String(issue.path[0])] = issue.path[0] === 'targetUrl' ? '请输入有效的 HTTP 或 HTTPS 地址，不含账号密码。' : issue.path[0] === 'outputDirectory' ? '请先选择一个本地输出目录。' : '请确认你拥有目标或已取得测试授权。'; setErrors(next); if (next.targetUrl) urlRef.current?.focus(); else if (next.outputDirectory) directoryRef.current?.focus(); else authRef.current?.focus(); return; } setErrors({}); await onStart(input); };
  const choose = async () => { setChoosing(true); try { const r: ApiResult<string | null> = window.mediaLab ? await window.mediaLab.chooseOutputDirectory() : { ok: false, error: { code: 'OPERATION_FAILED', message: '请在桌面应用中选择输出目录。' } }; if (!r.ok) setErrors(e => ({ ...e, outputDirectory: r.error.message })); else if (r.value) { setDirectory(r.value); setErrors(e => ({ ...e, outputDirectory: '' })); } } catch { setErrors(e => ({ ...e, outputDirectory: '目录选择未完成，请重试。' })); } finally { setChoosing(false); } };
  return <form className="new-run-form" noValidate onSubmit={submit}><div className="form-section"><div className="field-heading"><label htmlFor="target-url">目标播放页面</label><span>一个页面 · 明确授权</span></div><div className="url-field"><input ref={urlRef} id="target-url" type={showUrl ? 'url' : 'password'} inputMode="url" autoComplete="off" spellCheck={false} value={targetUrl} onChange={e => setUrl(e.target.value)} placeholder="https://example.com/watch" aria-invalid={!!errors.targetUrl} aria-describedby="url-help" /><button type="button" className="button ghost" onClick={() => setShowUrl(v => !v)} aria-pressed={showUrl}>{showUrl ? '隐藏地址' : '显示地址'}</button></div><p id="url-help" className={`field-help ${errors.targetUrl ? 'error-text' : ''}`}>{errors.targetUrl || '仅支持无需登录的公开播放页；地址中的敏感参数将被脱敏。'}</p><label htmlFor="output-directory">证据输出目录</label><div className="directory-field"><output id="output-directory">{outputDirectory || '尚未选择本地目录'}</output><button ref={directoryRef} type="button" className="button outline" onClick={() => void choose()} disabled={choosing || busy} aria-describedby="directory-help">{choosing ? '正在选择…' : '选择目录'}</button></div><p id="directory-help" className={`field-help ${errors.outputDirectory ? 'error-text' : ''}`}>{errors.outputDirectory || '报告与验证文件保存在本机，不上传至云端。'}</p></div><fieldset className="mode-fieldset"><legend>验证深度</legend>{([{ id: 'observe', title: '只观察', detail: '记录页面、Worker 和媒体管线，不重放请求。', code: '01' }, { id: 'standard', title: '标准安全验证', detail: '短范围采样、访问条件变体与服务端证据。', code: '02' }, { id: 'full-download', title: '完整下载验证', detail: '先完成标准验证，再由你点击开始下载与无损封装。', code: '03' }] as const).map(m => <label key={m.id} className={`mode-option ${mode === m.id ? 'mode-selected' : ''}`}><input type="radio" name="mode" value={m.id} checked={mode === m.id} onChange={() => setMode(m.id)} /><span><strong>{m.title}</strong><small>{m.detail}</small></span><span className="mode-code" aria-hidden="true">{m.code}</span></label>)}</fieldset><div className="concurrency-field"><label htmlFor="concurrency">最大请求并发</label><select id="concurrency" value={maxConcurrency} onChange={e => setConcurrency(Number(e.target.value))}>{[1, 2, 3, 4].map(n => <option key={n} value={n}>{n} 路</option>)}</select><span>所有后台任务均可取消</span></div><div className="authorization"><label><input ref={authRef} type="checkbox" checked={authorized} onChange={e => setAuthorized(e.target.checked)} aria-invalid={!!errors.authorizationConfirmed} aria-describedby="authorization-help" /><span>我拥有该目标，或已获得对该页面及其媒体请求的测试授权。</span></label><p id="authorization-help" className={`field-help ${errors.authorizationConfirmed ? 'error-text' : ''}`}>{errors.authorizationConfirmed || '测试不会尝试 DRM 绕过、许可证获取或媒体解密。'}</p></div><button type="submit" className="button primary start-button" disabled={busy || choosing} aria-busy={busy}>{busy ? '正在创建运行…' : '开始授权测试'}<span aria-hidden="true">→</span></button></form>;
}
