import type { ReactNode } from 'react';
export const statusLabels: Record<string, string> = { observing: '正在观察', probing: '正在验证', ready: '等待下载确认', downloading: '正在下载', reporting: '正在生成报告', completed: '已完成', partial: '部分完成', interrupted: '运行已中断', queued: '等待执行', running: '执行中', succeeded: '已完成', denied: '服务端拒绝', warning: '证据受限', failed: '执行异常', cancelled: '已取消', accessible: '媒体可访问', inconclusive: '无法判定', encrypted: '检测到加密', verified: '已验证', unverified: '尚未验证' };
export function Status({ value }: { value: string }) { return <span className={`status status-${value}`}><span aria-hidden="true" className="status-dot" />{statusLabels[value] ?? '等待证据'}</span>; }
export function Panel({ title, number, children, className = '', aside }: { title: string; number?: string; children: ReactNode; className?: string; aside?: ReactNode }) { return <section className={`panel ${className}`}><header className="panel-heading"><h2>{number && <span className="section-number">{number}</span>}{title}</h2>{aside}</header>{children}</section>; }
export function Empty({ title, children }: { title: string; children?: ReactNode }) { return <div className="empty-state"><span aria-hidden="true" className="empty-rule">—</span><strong>{title}</strong><p>{children}</p></div>; }
export const formatBytes = (n?: number) => n === undefined ? '未知大小' : n < 1024 ? `${n} B` : n < 1024 ** 2 ? `${(n / 1024).toFixed(1)} KB` : `${(n / 1024 ** 2).toFixed(2)} MB`;
export const formatTime = (value: string) => new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).format(new Date(value));
export const actionLabels: Record<string, string> = { 'navigation': '页面导航', 'target-attached': '附加页面 / Worker', 'target-detached': '目标已分离', 'capture-mse': 'MSE 追加与缓冲', 'capture-network': '网络请求', 'capture-frame': '页面框架', 'without-query': '删除查询参数', 'without-cookie': '移除 Cookie', 'without-referer': '移除 Referer', 'without-origin': '移除 Origin', 'range-head': '头部 Range', 'range-middle': '中部 Range', 'range-tail': '尾部 Range', 'range-full': '完整 Range 请求', 'range-concurrent': '有限并发 Range', 'expiry-replay': '到期后重放', 'baseline': '原始请求基线', 'download': '下载与字节校验', 'remux': 'FFmpeg 无损封装', 'probe': 'ffprobe 文件验证', 'run-start': '创建授权运行', 'run-complete': '完成运行与报告', 'run-cancel': '取消运行', 'browser-create': '创建隔离预览', 'browser-close': '关闭目标预览', 'target-initialize': '初始化目标页面', 'first-media-candidate': '发现首个媒体候选', 'debugger-attach': '连接 CDP', 'capture-stop': '结束媒体观察', 'state': '运行阶段更新', 'workbench': '记录运行异常', 'track-retrieval': '轨道下载验证' };
export function actionLabel(action: string): string { const name = action.split(':')[0]; if (name.startsWith('cdp-')) return `CDP · ${name.slice(4)}`; return actionLabels[name] ?? '记录观察证据'; }
